language: php

cache:
  directories:
    - ~/.composer/cache

services:
    - redis-server

php:
  - 5.4

sudo: false

before_install:
  - phpenv config-add .travis.php.ini

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: ba11992087a6a701b9ff4a8b009495ed075a1152087e546b534241bfea1f6644 

after_script:
  - ./bin/test-reporter
