parameters:
    open_orchestra_base.listener.locale.class : OpenOrchestra\BaseBundle\EventListener\LocaleListener
    open_orchestra_base.manager.encryption.class: OpenOrchestra\BaseBundle\Manager\EncryptionManager
    open_orchestra_base.manager.tag.class: OpenOrchestra\BaseBundle\Manager\TagManager
    open_orchestra_base.health_check.class: OpenOrchestra\BaseBundle\HealthCheck\HealthCheck
    open_orchestra_base.health_check.result.class: OpenOrchestra\BaseBundle\HealthCheck\HealthCheckResult
    open_orchestra_base.health_check.test_result.class: OpenOrchestra\BaseBundle\HealthCheck\HealthCheckTestResult

services:
    open_orchestra_base.locale_listener:
        class: '%open_orchestra_base.listener.locale.class%'
        arguments: ['%kernel.default_locale%']
        tags: [{name: kernel.event_subscriber}]
    open_orchestra_base.manager.encryption:
        class: '%open_orchestra_base.manager.encryption.class%'
        arguments:
            - '%open_orchestra_base.encryption_key%'
    open_orchestra_base.manager.tag:
        class: '%open_orchestra_base.manager.tag.class%'

    open_orchestra_base.health_check:
        class: '%open_orchestra_base.health_check.class%'
        arguments:
          - '%open_orchestra_base.health_check.result.class%'
